name = "svelte-starter"
compatibility_date = "2024-09-25"
pages_build_output_dir = ".svelte-kit/cloudflare"

[[d1_databases]]
binding = "DATABASE"
database_name = "svelte-starter-db"
database_id = "a6d7320a-0b73-4c0f-9043-17ea699a0484"

